routes/web.php
<?php

$this->group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin'], function(){
	
	/***
	* Home Admin
	***/
	$this->get('/', 'AdminController@index')->name('Admin.home');

	/***
	*CRUD Fornecedor
	***/
	$this->resource('fornecedores', 'FornecedorController');

	/***
	*CRUD Produto
	***/
	$this->resource('produtos', 'ProdutoController');

	/***
	*CRUD Pedido
	***/
	$this->resource('pedidos', 'PedidoController');
	$this->get('pendentes', 'PedidoController@pedidosPendentes')->name('pedidos.pendentes');
	$this->get('meuspedidos', 'PedidoController@meusPedidos')->name('meuspedidos');	

	

});

/***
	*Rotas Site Web(Vitrine) 
	***/
$this->get('/', 'Site\SiteController@index');

Route::get('carrinho/{produtos}', 'Site\SiteController@carrinhoCompras')->name('carrinhoCompras');

/***
*PedidoFinalizar
***/
$this->post('carrinhoFinalizar/', 'Admin\PedidoController@carrinhoFinalizar')->name('carrinho.finalizar');

//Route::post('carrinhoFinalizar/', 'Site\SiteController@carrinhoFinalizar')->name('carrinho.finalizar1');

Auth::routes();

app/Http/Controllers/Admin/ProdutoController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Provider; //Fornecedor
use App\Models\Category; //Categoria
use App\Models\Product; //Produto
use App\Http\Requests\ProdutoValidationFormRequest;

class ProdutoController extends Controller
{

    private $produto;

    public function __construct(Product $produto){
        $this->produto = $produto;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produtos = $this->produto->all();

        return view('admin.produto.listar-produtos',compact('produtos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fornecedores = Provider::all();
        $categorias = Category::all();
        return view('admin/produto/formulario-produto',compact('fornecedores','categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProdutoValidationFormRequest $request)
    {
        //dd($request->all());
        //dd($request->all());
        $formDados = $request->all();
        
        //if(!$request->fornecedores || $request->fornecedores[0] == null) //Verifica se algum registro de fornecedor foi informado
        //   $formDados['fornecedores'] = null;        

        $retorno = $this->produto->novoProduto($formDados);

        if($retorno['sucesso'])
            return redirect()
                    ->route('produtos.index')
                    ->with('sucesso',$retorno['mensagem']);

        return redirect()
                    ->back()
                    ->with('error',$retorno['mensagem']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //Carregamento Eager 
        $produto = $this->produto->where('id',$id)->with(['fornecedor'],['categoria'])->get()->first();

        return view('admin/produto/dados-produto',compact('produto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $fornecedores = Provider::all();
        $categorias = Category::all();

        //Carregamento Eager 
        $produto = $this->produto->where('id',$id)->with(['fornecedor'],['categoria'])->get()->first();

        //dd($produto->fornecedores);

        //dd($produtos);
        return view('admin/produto/formulario-produto',compact('fornecedores','produto','categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProdutoValidationFormRequest $request, $id)
    {
        $formDados = $request->all();       

        //$this->fornecedor::find($id);
        $produto = $this->produto::find($id);

        $retorno = $produto->atualizarDados($formDados);

        if($retorno['sucesso'])
            return redirect()
                    ->route('produtos.index')
                    ->with('sucesso',$retorno['mensagem']);

        return redirect()
                    ->back()
                    ->with('error',$retorno['mensagem']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/produto/dados-produto.blade.php
@extends('adminlte::page')

@section('title', 'Dados Produto')

@section('content_header')
    <h1>
        Produto 
        <small>Dados</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li><a href="{{route('produtos.index')}}">Produtos</a></li>
    	<li>Informações</li>        
    </ol>
@stop

@section('content')
	
	@include('includes/alertas')

   <!-- right column -->
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Dados Gerais</h3>

              <div class="box-tools pull-right">
                <a href="{{ route('produtos.index') }}" class="btn btn-default btn-group"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>

                <a href="{{ route('produtos.show',$produto->id) }}" class="btn btn-danger btn-group"><i class="fa fa-trash" aria-hidden="true"></i> Excluir</a>
                
                <a href="{{ route('produtos.edit',$produto->id) }}")}}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i>Atualizar</a>
              </div>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal">
              <div class="box-body">
                
                <table class="table table-bordered">
                  <thead>
                    
                  </thead>
                  <tbody>
                    <tr>
                      <tr class="info">
                        <th colspan="10">Dados do Produto</th>
                      </tr>
                      <th class="warning" colspan="1">Nome</th>
                      <td colspan="3">{{$produto->name}}</td>
                      <th class="warning" colspan="1">Categoria</th>
                      <td colspan="3">{{$produto->categoria->name}}</td>
                    </tr>
                    <tr>
                      <th class="warning" colspan="1">Descrição</th>
                      <td colspan="9">{{$produto->description}}</td>
                    </tr>
                    <tr>
                      <tr class="info">
                        <th colspan="10">Dados de Valores</th>
                      </tr>
                      <th class="warning" colspan="2">Preço de Compra</th>
                      <td colspan="3">R$ {{ number_format($produto->purchase_value, 2, ',', '.' ) }}</td>
                      <th class="warning" colspan="2">Preço de Venda</th>
                      <td colspan="3">R$ {{ number_format($produto->sale_value, 2, ',', '.' ) }}</td>
                    </tr>
                  </tbody>
                </table>

              </div>

            </form>
          </div>
          <!-- /.box -->
        </div>

        <div class="col-md-12">
          <div class="box box-default">
            <div class="box-header with-border">
              <h3 class="box-title">Fornecedor</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
              </div>
            </div>
            
            <div class="box-body" style="">

                <table class="table table-bordered">
                  <thead>
                    
                  </thead>
                  <tbody>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados do Fornecedor</th>
                      </tr>
                      <th class="warning" colspan="1">Nome</th>
                      <td colspan="2">{{$produto->fornecedor->name}}</td>
                      <th class="warning" colspan="1">CNPJ</th>
                      <td colspan="2">{{$produto->fornecedor->cnpj}}</td>
                    </tr>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados de Endereço</th>
                      </tr>
                      <th class="warning" colspan="1">Rua</th>
                      <td colspan="3">{{$produto->fornecedor->endereco->street}}</td>
                      <th class="warning" colspan="1">Número</th>
                      <td colspan="1">{{$produto->fornecedor->endereco->number}}</td>
                    </tr>
                    <tr>
                      <th class="warning" colspan="1">Cidade</th>
                      <td colspan="1"> {{$produto->fornecedor->endereco->city}} </td>
                      <th class="warning" colspan="1">Estado</th>
                      <td colspan="1"> {{$produto->fornecedor->endereco->state}} </td>
                      <th class="warning" colspan="1">CEP</th>
                      <td colspan="1"> {{$produto->fornecedor->endereco->cep}} </td>
                    </tr>
                  </tbody>
                </table>           
              
            </div>
          </div>
        </div>


@stop

resources/views/admin/produto/formulario-produto.blade.php
@extends('adminlte::page')

@section('title', 'Novo Produto')

@section('content_header')
    <h1>
        Produtos 
        <small>Novo</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>    	
        <li><a href="{{route('produtos.index')}}"}>Produtos</a></li>
        <li>Cadastro</li>
    </ol>
@stop

@section('content')

    <div class="box">
    	
    	<div class="box-body">

    		@include('includes/alertas')

        @if( isset($produto) )
          <form action="{{ route('produtos.update', $produto->id) }}"  method="post">
          {!! method_field('PATCH') !!}
          
        @else
          <form action="{{route('produtos.store')}}" method="post" enctype="multipart/form-data">
        @endif

                {!! csrf_field() !!}

                <div class="row">
                  <div class="col-md-12">
                    <div class="box box-primary">
                      <div class="box-body">
                        <!-- Centered Tabs -->
                        <ul class="nav nav-tabs nav-justified">
                          <li class="active"><a href="#home">Dados do Produto</a></li>
                          <li><a href="#menu2">Valores</a></li>
                          <li><a href="#menu4">Fotos</a></li>
                        </ul>

                        <div class="tab-content">
                          <div id="home" class="tab-pane fade in active">
                            <br>
                              <div class="row">

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Nome</label>
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Informe nome..." value="{{ $produto->name or old('name') }}">
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="provider">Fornecedor</label>

		                                <select id="provider" name="provider_id" class="form-control">
		      			                    <option value="" > -- Selecione o fornecedor -- </option>
		      			                    @foreach ($fornecedores as $fornecedor)
		      			                    <option value="{{ $fornecedor->id }}"
		                                      @if( (isset($produto) && $produto->provider_id) or old('provider') == $fornecedor->id)
		                                        selected
		                                      @endif
		                                    > {{$fornecedor->name}} </option>
		      			                    @endforeach
		      			                </select>

                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="category">Categoria</label>
                                        <select id="category" name="category_id" class="form-control">
		      			                    <option value="" > -- Selecione a cetegoria -- </option>
		      			                    @foreach ($categorias as $categoria)
		      			                    <option value="{{ $categoria->id }}"
		                                      @if( (isset($produto) && $produto->category_id) or old('category') == $categoria->id)
		                                        selected
		                                      @endif
		                                    > {{$categoria->name}} </option>
		      			                    @endforeach
		      			                </select>
                                    </div>
                                </div>
                                
                            </div>

                            <div class="row">                
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="description">Descrição</label>
                                        <textarea class="form-control" rows="2" id="description" name="description" placeholder="Informe a descrição do produto..."> {{ $produto->description or old('description') }}</textarea>
                                    </div>
                                </div>
                            </div>

                          </div>

                        <div id="menu2" class="tab-pane fade">
                            <br>
                              <div class="row">

                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="valor_compra">Preço de Compra</label>
                                      <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                        <input class="form-control dinheiro" step="1" placeholder="0.00 " id="valor_compra" name="purchase_value" type="number" value="{{ $produto->purchase_value or old('puchase_value') }}">
                                        <span class="input-group-addon">por unidade</span>
                                      </div>                      
                                    </div>
                                  </div>
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <label for="valor_venda">Valor de Venda</label>
                                      <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-dollar"></i></span>
                                        <input class="form-control dinheiro" step="1" placeholder="0.00" id="valor_venda" name="sale_value" type="number" value="{{ $produto->sale_value or old('sale_value') }}">
                                        <span class="input-group-addon">por unidade</span>
                                      </div>                      
                                    </div>
                                  </div>

                              </div>
                          </div>

                          <div id="menu4" class="tab-pane fade">
                            <br>
                              <div class="row" >
                                <div class="col-md-12">
                                  <div class="input-group" >
                                     <label>Fotos apenas no formato .PNG ou .JPG</label>     
                                  </div>         
                                </div>
                              </div>
                              <div class="row" >
                                <div class="col-md-12">
                                  <div class="input-group" >
                                    <img id="blah" src="http://placehold.it/300" alt="your image" />     
                                  </div>         
                                </div>
                              </div>

                              <div class="row " >
                                <div class="col-md-12">
                                  <div class="input-group">
                                    <input name='' id="" type='file' class="form-control-file" onchange="readURL(this);" />  
                                  </div>                        
                                </div>
                              </div>

                          </div>

                        </div>

                      </div>

                      <div class="box-footer">
                        <input type="submit" value="Salvar" class="submit btn btn-primary pull-right">
                      </div>
                    </div>
                  </div>
                </div>

              </form>

    	</div>
    </div>
@stop

@section('css')
  <style type="text/css">
    
    img {
      max-width:300px;
    } 
    
  </style>

@stop

@section('js')
    <script>

        // Responsável por controler os TABS do Form
          $(document).ready(function(){
              $(".nav-tabs a").click(function(){
                  $(this).tab('show');
              });      
          });

          //Responsável por carregar as fotos
          function readURL(input) {
            if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function (e) {
                  $('#blah').attr('src', e.target.result);
              };

              reader.readAsDataURL(input.files[0]);
            }
          }

          //$('.dinheiro').mask('#.##0,00', {reverse: true});

    </script>
@stop

resources/views/admin/produto/listar-produtos.blade.php
@extends('adminlte::page')

@section('title', 'Produtos')

@section('content_header')
    <h1>
        Produtos 
        <small>Lista</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li>Lista</li>
        <li>Produtos</li>
    </ol>
@stop

@section('content')
    
    

    <div class="row">
        <form action="" method="post">
            <div class="col-md-12">
                <div class="box box-default collapsed-box box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">Pesquisa Avançada</h3>
                        <div class="box-tools pull-right">
                          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                        </div>
                    </div>

                <div class="box-body">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="nome_pesquisa">Nome</label>
                          <input type="text" class="form-control" id="nome_pesquisa" name="nome_pesquisa" placeholder="Pesquisar por nome...">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="cnpj_pesquisa">Código</label>
                          <input type="text" class="form-control" id="cnpj_pesquisa" name="cnpj_pesquisa" placeholder="Pesquisar por CNPJ...">
                        </div>
                      </div>
                      <div class="col-md-2">
                        <button type="submit" class="btn btn-success btn-block" style="margin-top: 17%">Pesquisar</button>
                      </div>
                    </div>
                </div>
              
                </div> 
            </div>
        </form>
    </div>


    <div class="box">

        <div class="box-header">
            <div class="container-fluid">
        <div class="row">            
            <a href="{{ route('produtos.create') }}" class="btn btn-primary btn-lg pull-right"><i class="fa fa-plus" aria-hidden="true"></i> Novo Produto</a>
        </div>
    </div>
        </div>
    	
    	<div class="box-body">

    		@include('includes/alertas')

    		<table class="table table-bordered table-hover">
                <thead>
                    <tr class="info">
                        <th >Imagem</th>
                        <th >Nome</th>
                        <th >Descrição</th>
                        <th >Valor Compra</th>
                        <th >Valor Venda</th>
                        <th >Ações</th>
                    <tr>
                </thead>
                <tbody>
                    @forelse($produtos as $produto)
                        <tr>
                            <td> {{ $produto->imagem }} </td>
                            <td> {{ $produto->name }} </td>
                            <td> {{ $produto->description }} </td>
                            <td>R$ {{ number_format($produto->purchase_value, 2, ',', '.' ) }} </td>
                            <td>R$ {{ number_format($produto->sale_value, 2, ',', '.' ) }} </td>                            
                            <td style="text-align: right;" >
                              <a href="{{ route('produtos.show',$produto->id) }}" class="btn btn-info btn-group"><i class="fa fa-eye" aria-hidden="true"></i></a>
                              <a href="{{ route('produtos.edit',$produto->id) }}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    @empty
                        <p>Não foram encontrados registros</p>
                    @endforelse
                </tbody>      
            </table>

    	</div>
    </div>
@stop