routes/web.php
<?php

$this->group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin'], function(){
	
	/***
	* Home Admin
	***/
	$this->get('/', 'AdminController@index')->name('Admin.home');

	/***
	*CRUD Fornecedor
	***/
	$this->resource('fornecedores', 'FornecedorController');

	/***
	*CRUD Produto
	***/
	$this->resource('produtos', 'ProdutoController');

	/***
	*CRUD Pedido
	***/
	$this->resource('pedidos', 'PedidoController');
	$this->get('pendentes', 'PedidoController@pedidosPendentes')->name('pedidos.pendentes');
	$this->get('meuspedidos', 'PedidoController@meusPedidos')->name('meuspedidos');	

	

});

/***
	*Rotas Site Web(Vitrine) 
	***/
$this->get('/', 'Site\SiteController@index');

Route::get('carrinho/{produtos}', 'Site\SiteController@carrinhoCompras')->name('carrinhoCompras');

/***
*PedidoFinalizar
***/
$this->post('carrinhoFinalizar/', 'Admin\PedidoController@carrinhoFinalizar')->name('carrinho.finalizar');

//Route::post('carrinhoFinalizar/', 'Site\SiteController@carrinhoFinalizar')->name('carrinho.finalizar1');

Auth::routes();

app/Http/Controllers/Admin/PedidoController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Order; //Pedidos
use App\Models\Cart; //Carrinho
use Gate; 
use App\Http\Requests\PedidoCompraValidationFormRequest;
use App\Http\Requests\PedidoValidationFormRequest;

class PedidoController extends Controller
{

    private $pedido;

    public function __construct(Order $pedido){
        $this->pedido = $pedido;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Retorna todos os pedidos
        $pedidos = $this->pedido->all();

        return view('admin.pedido.listar-pedidos',compact('pedidos'));
    }

    public function pedidosPendentes()
    {
        //Retorna todos os pedidos
        $pedidos = $this->pedido->where('state','Aguardando')->get();
        return view('admin.pedido.listar-pedidos-pendentes',compact('pedidos'));
    }

    public function meusPedidos()
    {
        //Retorna todos os pedidos
        $pedidos = $this->pedido->where('user_id',auth()->user()->id)->get();
        return view('admin.meuspedidos.listar-pedidos',compact('pedidos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //Carregamento Eager
        
        $pedido = $this->pedido->where('id',$id)->with(['endereco','usuario'])->get()->first();;
        $carrinhos = Cart::where('order_id',$id)->get();
        //dd($carrinhos);
        return view('admin.pedido.atualizar-pedido',compact('pedido','carrinhos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        dd($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PedidoValidationFormRequest $request, $id)
    {
        $formDados = $request->all();

        $pedido = $this->pedido::find($id);

        $retorno = $pedido->atualizarSituacao($formDados);

        if($retorno['sucesso'])
            return redirect()
                    ->route('pedidos.index')
                    ->with('sucesso',$retorno['mensagem']);

        return redirect()
                    ->back()
                    ->with('error',$retorno['mensagem']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function carrinhoFinalizar(PedidoCompraValidationFormRequest $request){
        //antes verificar se campos preenchidos
        if(auth()->check()){
            $formDados = $request->all();
        
            $retorno = $this->pedido->novoPedido($formDados);

            if($retorno['sucesso'])
                return redirect()
                        ->route('meuspedidos')
                        ->with('sucesso',$retorno['mensagem']);

            return redirect()
                        ->back()
                        ->with('error',$retorno['mensagem']);
        }else{
            return redirect()->route('login');
        }
        
    }
}

resources/views/admin/pedido/atualizar-pedido.blade.php
@extends('adminlte::page')

@section('title', 'Dados Pedido')

@section('content_header')
    <h1>
        Pedido 
        <small>Dados</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li><a href="{{route('fornecedores.index')}}">Pedido</a></li>
    	<li>Informações</li>        
    </ol>
@stop

@section('content')
	
	@include('includes/alertas')

   <!-- right column -->
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Dados Gerais</h3>
              <div class="box-tools pull-right">
                <a href="" class="btn btn-default btn-group"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>

                
              </div>
            </div>
            <!-- /.box-header -->
          
              <div class="box-body">
                
                <table class="table table-bordered">
                  <thead>

                    <form action="{{ route('pedidos.update', $pedido->id) }}"  method="post">
                      {!! method_field('PATCH') !!}
                      {!! csrf_field() !!}
                      <div class="col-md-5">
                        <div class="form-group">
                          <label for="state">Situação Pedido</label>

                          <select id="state" name="state" class="form-control">
                            <option value="" > -- Selecione o Situação -- </option>
                            <option value="Aprovado" 
                              @if( (isset($pedido) && $pedido->state == 'Aprovado' ) ) 
                                selected 
                              @endif >Aprovado</option>
                            <option value="Cancelado"
                              @if( (isset($pedido) && $pedido->state == 'Cancelado' ) ) 
                                selected 
                              @endif >Cancelado</option>
                            <option value="Aguardando" 
                              @if( (isset($pedido) && $pedido->state == 'Aguardando' ) ) 
                                selected 
                              @endif >Aguardando</option>
                            <option value="Encaminhado" 
                              @if( (isset($pedido) && $pedido->state == 'Encaminhado' ) ) 
                                selected 
                              @endif >Encaminhado</option>
                            <option value="Entregue" 
                              @if( (isset($pedido) && $pedido->state == 'Entregue' ) ) 
                                selected 
                              @endif  >Entregue</option>   
                          </select>

                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group">
                          <label for="state_sale">Situação Pagamento</label>

                          <select id="state_sale" name="state_sale" class="form-control">
                            <option value="" > -- Selecione o estado -- </option>
                            <option value="Confirmado" 
                              @if( (isset($pedido) && $pedido->state_sale == 'Confirmado' )  ) 
                                selected 
                              @endif >Confirmado</option>
                            <option value="Cancelado" 
                              @if( (isset($pedido) && $pedido->state_sale == 'Cancelado' )  ) 
                                selected 
                              @endif >Cancelado</option>
                            <option value="Aguardando" 
                              @if( (isset($pedido) && $pedido->state_sale == 'Aguardando' )  ) 
                                selected 
                              @endif >Aguardando</option>  
                          </select>

                          

                        </div>
                      </div>
                      <div class="col-md-1">
                        <div class="form-group">
                          <label for="state">----</label>
                          <input type="submit" value="Atualizar" class="submit btn btn-warning pull-right">
                        </div>
                      </div>
                    </form>
                    
                  </thead>
                  <tbody>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados do Cliente</th>
                      </tr>
                      <th class="warning" colspan="1">Nome</th>
                      <td colspan="2">{{$pedido->usuario->name}}</td>
                      <th class="warning" colspan="1">Email</th>
                      <td colspan="2">{{$pedido->usuario->email}}</td>
                    </tr>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados do Pedido</th>
                      </tr>
                      <th class="warning" colspan="1">Data</th>
                      <td colspan="2">{{$pedido->getDataAttribute($pedido->date)}}</td>
                      <th class="warning" colspan="1">Total Pedido</th>
                      <td colspan="2">R$ {{ number_format($pedido->total_final, 2, ',', '.' ) }}</td>
                    </tr>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Endereço de Entrega</th>
                      </tr>
                      <th class="warning" colspan="1">Rua</th>
                      <td colspan="3">{{$pedido->endereco->street}}</td>
                      <th class="warning" colspan="1">Número</th>
                      <td colspan="1">{{$pedido->endereco->number}}</td>
                    </tr>
                    <tr>
                      <th class="warning" colspan="1">Cidade</th>
                      <td colspan="1"> {{$pedido->endereco->city}} </td>
                      <th class="warning" colspan="1">Estado</th>
                      <td colspan="1"> {{$pedido->endereco->state}} </td>
                      <th class="warning" colspan="1">CEP</th>
                      <td colspan="1"> {{$pedido->endereco->cep}} </td>
                    </tr>
                  </tbody>
                </table>

              </div>
              
              <div class="box-footer">
                <h2>Produtos</h2>

                <table class="table table-bordered table-hover">
                  <thead>
                      <tr class="info">
                        <th >Imagem</th>
                        <th >Produto</th>
                        <th >Valor Unitário</th>
                        <th >Quantidade</th>
                        <th >SubTotal</th>
                      <tr>
                  </thead>
                  <tbody>
                    @forelse($carrinhos as $carrinho)
                      <tr>
                        <td> {{ $carrinho->produto->imagem }} </td>
                        <td> {{ $carrinho->produto->name }} </td>
                        <td> R$ {{ number_format($carrinho->produto->sale_value, 2, ',', '.' ) }} </td>
                        <td> {{ $carrinho->amount }} </td>
                        <td> R$ {{ number_format($carrinho->total, 2, ',', '.' ) }} </td>
                      </tr>
                        
                    @empty
                        <p>Não foram encontrados registros</p>
                    @endforelse
                  </tbody>      
                </table>
                
              </div>
              <!-- /.box-footer -->
            
          </div>
          <!-- /.box -->

@stop

resources/views/admin/pedido/dados-pedido.blade.php
@extends('adminlte::page')

@section('title', 'Dados Pedido')

@section('content_header')
    <h1>
        Pedido 
        <small>Dados</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li><a href="{{route('fornecedores.index')}}">Pedido</a></li>
    	<li>Informações</li>        
    </ol>
@stop

@section('content')
	
	@include('includes/alertas')

   <!-- right column -->
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Dados Gerais</h3>
              <div class="box-tools pull-right">
                <a href="" class="btn btn-default btn-group"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>

                <a href="")}}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i>Atualizar</a>
              </div>
            </div>
            <!-- /.box-header -->
            <form class="form-horizontal">
              <div class="box-body">
                
                <table class="table table-bordered">
                  <thead>
                    
                  </thead>
                  <tbody>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados do Cliente</th>
                      </tr>
                      <th class="warning" colspan="1">Nome</th>
                      <td colspan="2">{{$pedido->usuario->name}}</td>
                      <th class="warning" colspan="1">Email</th>
                      <td colspan="2">{{$pedido->usuario->email}}</td>
                    </tr>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados do Pedido</th>
                      </tr>
                      <th class="warning" colspan="1">Data</th>
                      <td colspan="2">{{$pedido->date}}</td>
                      <th class="warning" colspan="1">Total Pedido</th>
                      <td colspan="2">{{$pedido->total_final}}</td>
                    </tr>
                    <tr>
                      <th class="warning" colspan="1">Situação Pedido</th>
                      <td colspan="2">{{$pedido->state}}</td>
                      <th class="warning" colspan="1">Situação Pagamento</th>
                      <td colspan="2">{{$pedido->state_sale}}</td>
                    </tr>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Endereço de Entrega</th>
                      </tr>
                      <th class="warning" colspan="1">Rua</th>
                      <td colspan="3">{{$pedido->endereco->street}}</td>
                      <th class="warning" colspan="1">Número</th>
                      <td colspan="1">{{$pedido->endereco->number}}</td>
                    </tr>
                    <tr>
                      <th class="warning" colspan="1">Cidade</th>
                      <td colspan="1"> {{$pedido->endereco->city}} </td>
                      <th class="warning" colspan="1">Estado</th>
                      <td colspan="1"> {{$pedido->endereco->state}} </td>
                      <th class="warning" colspan="1">CEP</th>
                      <td colspan="1"> {{$pedido->endereco->cep}} </td>
                    </tr>
                  </tbody>
                </table>

              </div>
              
              <div class="box-footer">
                <h2>Produtos</h2>

                <table class="table table-bordered table-hover">
                  <thead>
                      <tr class="info">
                        <th >Imagem</th>
                        <th >Produto</th>
                        <th >Valor Unitário</th>
                        <th >Quantidade</th>
                        <th >SubTotal</th>
                      <tr>
                  </thead>
                  <tbody>
                    @forelse($carrinhos as $carrinho)
                      <tr>
                        <td> {{ $carrinho->produto->imagem }} </td>
                        <td> {{ $carrinho->produto->name }} </td>
                        <td> {{ $carrinho->produto->sale_value }} </td>
                        <td> {{ $carrinho->amount }} </td>
                        <td> {{ $carrinho->total }} </td>
                      </tr>
                        
                    @empty
                        <p>Não foram encontrados registros</p>
                    @endforelse
                  </tbody>      
                </table>
                
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
          <!-- /.box -->

@stop

resources/views/admin/pedido/listar-pedidos-pendentes.blade.php
@extends('adminlte::page')

@section('title', 'Pedidos')

@section('content_header')
    <h1>
        Pedidos 
        <small>Lista</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li>Lista</li>
        <li>Pedidos</li>
    </ol>
@stop

@section('content')
    
    <div class="row">
            <form action="" method="post">
                <div class="col-md-12">
                    <div class="box box-default collapsed-box box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">Pesquisa Avançada</h3>
                            <div class="box-tools pull-right">
                              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>

                    <div class="box-body">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="nome_pesquisa">Nome</label>
                              <input type="text" class="form-control" id="nome_pesquisa" name="nome_pesquisa" placeholder="Pesquisar por nome...">
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="cnpj_pesquisa">CNPJ</label>
                              <input type="text" class="form-control" id="cnpj_pesquisa" name="cnpj_pesquisa" placeholder="Pesquisar por CNPJ...">
                            </div>
                          </div>
                          <div class="col-md-2">
                            <button type="submit" class="btn btn-success btn-block" style="margin-top: 17%">Pesquisar</button>
                          </div>
                        </div>
                    </div>
                  
                    </div> 
                </div>
            </form>
    </div>


    <div class="box">
    	
    	<div class="box-body">

    		@include('includes/alertas')

    		<table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="col-md-3">Cliente</th>
                        <th class="col-md-2">Data</th>
                        <th class="col-md-1">Total</th>
                        <th class="col-md-2">Situação</th>
                        <th class="col-md-2">Situação Pagamento</th>
                        <th class="col-md-2">Ação</th>
                    <tr>
                </thead>
                <tbody>
                    @forelse($pedidos as $pedido)
                        
                        <tr>
                            <td> {{ $pedido->usuario->name }} </td>
                            <td> {{ $pedido->getDataAttribute($pedido->date) }} </td>
                            <td> R$ {{ number_format($pedido->total_final, 2, ',', '.' ) }} </td>
                            <td> {{ $pedido->state }} </td>
                            <td> {{ $pedido->state_sale }} </td>
                            <td style="text-align: right;" >
                                       
                                <a href="{{ route('pedidos.show',$pedido->id) }}" class="btn btn-info btn-group"><i class="fa fa-eye" aria-hidden="true"></i> Ver</a>
                                        
                                <a href="{{ route('pedidos.edit',$pedido->id) }}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i> Atualizar</a>
                                    
                            </td>
                        </tr>
                        
                    @empty
                        <p>Não foram encontrados registros</p>
                    @endforelse
                </tbody>      
            </table>

    	</div>
    </div>
@stop

resources/views/admin/pedido/listar-pedidos.blade.php
@extends('adminlte::page')

@section('title', 'Pedidos')

@section('content_header')
    <h1>
        Pedidos 
        <small>Lista</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li>Lista</li>
        <li>Pedidos</li>
    </ol>
@stop

@section('content')
    
    <div class="row">
            <form action="" method="post">
                <div class="col-md-12">
                    <div class="box box-default collapsed-box box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">Pesquisa Avançada</h3>
                            <div class="box-tools pull-right">
                              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>

                    <div class="box-body">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="nome_pesquisa">Nome</label>
                              <input type="text" class="form-control" id="nome_pesquisa" name="nome_pesquisa" placeholder="Pesquisar por nome...">
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="cnpj_pesquisa">CNPJ</label>
                              <input type="text" class="form-control" id="cnpj_pesquisa" name="cnpj_pesquisa" placeholder="Pesquisar por CNPJ...">
                            </div>
                          </div>
                          <div class="col-md-2">
                            <button type="submit" class="btn btn-success btn-block" style="margin-top: 17%">Pesquisar</button>
                          </div>
                        </div>
                    </div>
                  
                    </div> 
                </div>
            </form>
    </div>


    <div class="box">
    	
    	<div class="box-body">

    		@include('includes/alertas')

    		<table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="col-md-3">Cliente</th>
                        <th class="col-md-2">Data</th>
                        <th class="col-md-1">Total</th>
                        <th class="col-md-2">Situação</th>
                        <th class="col-md-2">Situação Pagamento</th>
                        <th class="col-md-2">Ação</th>
                    <tr>
                </thead>
                <tbody>
                    @forelse($pedidos as $pedido)
                        
                        <tr>
                            <td> {{ $pedido->usuario->name }} </td>
                            <td> {{ $pedido->getDataAttribute($pedido->date) }} </td>
                            <td> R$ {{ number_format($pedido->total_final, 2, ',', '.' ) }} </td>
                            <td> {{ $pedido->state }} </td>
                            <td> {{ $pedido->state_sale }} </td>
                            <td style="text-align: right;" >
                                       
                                <a href="{{ route('pedidos.show',$pedido->id) }}" class="btn btn-info btn-group"><i class="fa fa-eye" aria-hidden="true"></i> Ver</a>
                                        
                                <a href="{{ route('pedidos.edit',$pedido->id) }}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i> Atualizar</a>
                                    
                            </td>
                        </tr>
                        
                    @empty
                        <p>Não foram encontrados registros</p>
                    @endforelse
                </tbody>      
            </table>

    	</div>
    </div>
@stop