routes/web.php
<?php

$this->group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin'], function(){
	
	/***
	* Home Admin
	***/
	$this->get('/', 'AdminController@index')->name('Admin.home');

	/***
	*CRUD Fornecedor
	***/
	$this->resource('fornecedores', 'FornecedorController');

	/***
	*CRUD Produto
	***/
	$this->resource('produtos', 'ProdutoController');

	/***
	*CRUD Pedido
	***/
	$this->resource('pedidos', 'PedidoController');
	$this->get('pendentes', 'PedidoController@pedidosPendentes')->name('pedidos.pendentes');
	$this->get('meuspedidos', 'PedidoController@meusPedidos')->name('meuspedidos');	

	

});

/***
	*Rotas Site Web(Vitrine) 
	***/
$this->get('/', 'Site\SiteController@index');

Route::get('carrinho/{produtos}', 'Site\SiteController@carrinhoCompras')->name('carrinhoCompras');

/***
*PedidoFinalizar
***/
$this->post('carrinhoFinalizar/', 'Admin\PedidoController@carrinhoFinalizar')->name('carrinho.finalizar');

//Route::post('carrinhoFinalizar/', 'Site\SiteController@carrinhoFinalizar')->name('carrinho.finalizar1');

Auth::routes();

app/Http/Controllers/Admin/FornecedorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Provider; //Fornecedor
use App\Models\Address; //Endereço
use App\Http\Requests\FornecedorValidationFormRequest;
use Gate;

class FornecedorController extends Controller
{

    private $fornecedor;

    public function __construct(Provider $fornecedor){
        $this->fornecedor = $fornecedor;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $fornecedores = $this->fornecedor->all();

       // dd($fornecedores);


        return view('admin.fornecedor.listar-fornecedores',compact('fornecedores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $estados = ['Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Distrito Federal','Espírito Santo','Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais','Pará','Paraíba','Paraná','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo','Sergipe','Tocantins'];
        return view('admin/fornecedor/formulario-fornecedor',compact('estados'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FornecedorValidationFormRequest $request)
    {
        $formDados = $request->all();

        $retorno = $this->fornecedor->novoFornecedor($formDados);

        if($retorno['sucesso'])
            return redirect()
                    ->route('fornecedores.index')
                    ->with('sucesso',$retorno['mensagem']);

        return redirect()
                    ->back()
                    ->with('error',$retorno['mensagem']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $fornecedor = $this->fornecedor->where('id',$id)->with(['endereco'])->get()->first();

        return view('admin/fornecedor/dados-fornecedor',compact('fornecedor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //Carregamento Eager 
        $fornecedor = $this->fornecedor->where('id',$id)->with(['endereco'])->get()->first();
        
        $estados = ['Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Distrito Federal','Espírito Santo','Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais','Pará','Paraíba','Paraná','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo','Sergipe','Tocantins'];

        return view('admin/fornecedor/formulario-fornecedor', compact('estados', 'fornecedor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FornecedorValidationFormRequest $request, $id)
    {
        $dadosForm = $request->all();
        // $fornecedor = $this->fornecedor->where('id',$id)->with(['endereco'])->get()->first();
        $fornecedor = $this->fornecedor::find($id);

        $retorno = $fornecedor->atualizarDados($dadosForm);

        if($retorno['sucesso'])
            return redirect()
                    ->route('fornecedores.index')
                    ->with('sucesso',$retorno['mensagem']);

        return redirect()
                    ->back()
                    ->with('error',$retorno['mensagem']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/fornecedor/dados-fornecedor.blade.php
@extends('adminlte::page')

@section('title', 'Dados Fornecedor')

@section('content_header')
    <h1>
        Fornecedores 
        <small>Dados</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li><a href="{{route('fornecedores.index')}}">Fornecedores</a></li>
    	<li>Informações</li>        
    </ol>
@stop

@section('content')
	
	@include('includes/alertas')

   <!-- right column -->
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Dados Gerais</h3>
              <div class="box-tools pull-right">
                <a href="{{ route('fornecedores.index') }}" class="btn btn-default btn-group"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>

                  <a href="{{ route('fornecedores.show',$fornecedor->id) }}" class="btn btn-danger btn-group"><i class="fa fa-trash" aria-hidden="true"></i> Excluir</a>

                  <a href="{{ route('fornecedores.edit',$fornecedor->id) }}")}}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i>Atualizar</a>
              </div>
            </div>
            <!-- /.box-header -->
            <form class="form-horizontal">
              <div class="box-body">
                
                <table class="table table-bordered">
                  <thead>
                    
                  </thead>
                  <tbody>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados do Fornecedor</th>
                      </tr>
                      <th class="warning" colspan="1">Nome</th>
                      <td colspan="2">{{$fornecedor->name}}</td>
                      <th class="warning" colspan="1">CNPJ</th>
                      <td colspan="2">{{$fornecedor->cnpj}}</td>
                    </tr>
                    <tr>
                      <tr class="info">
                        <th colspan="6">Dados de Endereço</th>
                      </tr>
                      <th class="warning" colspan="1">Rua</th>
                      <td colspan="3">{{$fornecedor->endereco->street}}</td>
                      <th class="warning" colspan="1">Número</th>
                      <td colspan="1">{{$fornecedor->endereco->number}}</td>
                    </tr>
                    <tr>
                      <th class="warning" colspan="1">Cidade</th>
                      <td colspan="1"> {{$fornecedor->endereco->city}} </td>
                      <th class="warning" colspan="1">Estado</th>
                      <td colspan="1"> {{$fornecedor->endereco->state}} </td>
                      <th class="warning" colspan="1">CEP</th>
                      <td colspan="1"> {{$fornecedor->endereco->cep}} </td>
                    </tr>
                  </tbody>
                </table>

              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <h2>Produtos Fornecidos</h2>

                <table class="table table-bordered table-hover">
                  <thead>
                      <tr class="info">
                        <th >Imagem</th>
                        <th >Nome</th>
                        <th >Descrição</th>
                        <th >Valor Compra</th>
                        <th >Valor Venda</th>
                        <th >Ações</th>
                      <tr>
                  </thead>
                  <tbody>
                        @forelse($fornecedor->produtos as $produto)
                          <tr>
                            <td> {{ $produto->imagem }} </td>
                            <td> {{ $produto->name }} </td>
                            <td> {{ $produto->description }} </td>
                            <td>R$ {{ number_format($produto->purchase_value, 2, ',', '.' ) }} </td>
                            <td>R$ {{ number_format($produto->sale_value, 2, ',', '.' ) }} </td>                            
                            <td style="text-align: right;" >
                              <a href="{{ route('produtos.show',$produto->id) }}" class="btn btn-info btn-group"><i class="fa fa-eye" aria-hidden="true"></i></a>
                              <a href="{{ route('produtos.edit',$produto->id) }}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i></a>
                            </td>
                          </tr>
                        @empty
                            <p>Não foram encontrados registros</p>
                        @endforelse
                    </tbody>      
                </table>
                
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
          <!-- /.box -->

@stop

resources/views/admin/fornecedor/formulario-fornecedor.blade.php
@extends('adminlte::page')

@section('title', 'Novo Fornecedor')

@section('content_header')
    <h1>
        Fornecedores 
        <small>Novo</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li><a href="{{route('fornecedores.index')}}">Fornecedor</a></li>
    	<li>Cadastro</li>        
    </ol>
@stop

@section('content')
	
	@include('includes/alertas')

    @if( isset($fornecedor) )
      <form action="{{ route('fornecedores.update', $fornecedor->id) }}"  method="post">
      {!! method_field('PATCH') !!}
      
    @else
      <form action="{{ route('fornecedores.store') }}"  method="post">
    @endif            

    	{!! csrf_field() !!}

        <div class="row">
          <div class="col-md-12">
            <div class="box box-primary">
              <div class="box-header with-border">
                <h3 class="box-title">Dados do Fornecedor</h3>
                <div class="box-tools pull-right">
                  <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
              </div>

              <div class="box-body">
                <!-- Centered Tabs -->
                <ul class="nav nav-tabs nav-justified">
                  <li class="active"><a href="#empresa">Dados da Empresa</a></li>
                  <li><a href="#endereco">Dados de Endereço</a></li>
                </ul>

                <div class="tab-content">
                  <div id="empresa" class="tab-pane fade in active">
                    <br>
                      <div class="row">

                        <div class="col-md-8">
                            <div class="form-group">
                              <label for="name">Nome</label>
                              <input type="text" class="form-control" id="name" name="name" placeholder="Informe o nome..." value="{{ $fornecedor->name or old('name') }}" >
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                              <label for="cnpj">CNPJ</label>
                              <input type="text" class="form-control cnpj" id="cnpj" name="cnpj" placeholder="00.000.000/0000-00" value="{{ $fornecedor->cnpj or old('cnpj') }}" >
                            </div>
                        </div>
                        
                      </div>

                  </div>

                  <div id="endereco" class="tab-pane fade">
                    <br>
                      <div class="row">
                        <div class="col-md-10">
                          <div class="form-group">
                            <label for="street">Rua</label>
                            <input type="text" class="form-control" id="street" name="street" placeholder="Informe o nome da rua..." value="{{ $fornecedor->endereco->street or old('street') }}" >
                            <p class="help-block">Ex: Avenida Brasil</p>
                          </div>
                        </div>

                        <div class="col-md-2">
                          <div class="form-group">
                            <label for="number">Número</label>
                            <input type="text" class="form-control" id="number" name="number" placeholder="Informe o numero..." value="{{ $fornecedor->endereco->number or old('number') }}" >
                          </div>
                        </div>                                                
                      </div>

                      <div class="row">
                        <div class="col-md-6">
                          <div class="form-group">
                            <label for="city">Cidade</label>
                            <input type="text" class="form-control" id="city" name="city" placeholder="Informe a cidade..." value="{{ $fornecedor->endereco->city or old('city')}}" >
                          </div>
                        </div>

                        <div class="col-md-3">
                          <div class="form-group">
                            <label for="state">Estado</label>

                            <select id="state" name="state" class="form-control">
      			                    <option value="" > -- Selecione o estado -- </option>
      			                    @foreach ($estados as $estado)
      			                        <option value="{{ $estado }}"
                                      @if( (isset($fornecedor) && $fornecedor->endereco->state) or old('state') == $estado)
                                        selected
                                      @endif
                                    > {{$estado}} </option>
      			                    @endforeach
      			                </select>

                          </div>
                        </div>

                        <div class="col-md-3">
                          <div class="form-group">
                            <label for="cep">CEP</label>
                            <input type="text" class="form-control cep" id="cep" name="cep" placeholder="00000-000" value="{{ $fornecedor->endereco->cep or old('cep')}}" >
                          </div>
                        </div>
                      </div>
                  </div>                 
                </div>
              </div>

              <div class="box-footer">
                <input type="submit" value="Salvar" class="submit btn btn-primary pull-right">
              </div>
              
            </div>
          </div>
        </div>

      </form>
@stop

@section('js')
	<script src="{{ asset('js/jquery.mask.min.js') }}"></script>

  <script>

    // Responsável por controlar os TABS do Form
		$(document).ready(function(){
		  $(".nav-tabs a").click(function(){
		    $(this).tab('show');
		  });      
		});

		// Mascaras de campo
		$('.cnpj').mask('00.000.000/0000-00');
		$('.cep').mask('00000-000');
  </script>
@stop

resources/views/admin/fornecedor/listar-fornecedores.blade.php
@extends('adminlte::page')

@section('title', 'Fornecedores')

@section('content_header')
    <h1>
        Fornecedores 
        <small>Lista</small>
      </h1>
    <ol class="breadcrumb">
    	<li><a href="/admin">Dashboard</a></li>
    	<li>Lista</li>
        <li>Fornecedores</li>
    </ol>
@stop

@section('content')
    
    <div class="row">
            <form action="" method="post">
                <div class="col-md-12">
                    <div class="box box-default collapsed-box box-solid">
                        <div class="box-header with-border">
                            <h3 class="box-title">Pesquisa Avançada</h3>
                            <div class="box-tools pull-right">
                              <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>

                    <div class="box-body">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="nome_pesquisa">Nome</label>
                              <input type="text" class="form-control" id="nome_pesquisa" name="nome_pesquisa" placeholder="Pesquisar por nome...">
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="cnpj_pesquisa">CNPJ</label>
                              <input type="text" class="form-control" id="cnpj_pesquisa" name="cnpj_pesquisa" placeholder="Pesquisar por CNPJ...">
                            </div>
                          </div>
                          <div class="col-md-2">
                            <button type="submit" class="btn btn-success btn-block" style="margin-top: 17%">Pesquisar</button>
                          </div>
                        </div>
                    </div>
                  
                    </div> 
                </div>
            </form>
    </div>


    <div class="box">

        <div class="box-header">
            <div class="container-fluid">
        <div class="row">
                       
            <a href="{{ route('fornecedores.create') }}" class="btn btn-primary btn-lg pull-right"><i class="fa fa-truck" aria-hidden="true"></i> Novo Fornecedor</a>
            
        </div>
    </div>
        </div>
    	
    	<div class="box-body">

    		@include('includes/alertas')

    		<table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="col-md-4">Nome</th>
                        <th class="col-md-2">CNPJ</th>
                        <th class="col-md-2">Ações</th>
                    <tr>
                </thead>
                <tbody>
                    @forelse($fornecedores as $fornecedor)
                        
                            <tr>
                                <td> {{ $fornecedor->name }} </td>
                                <td> {{ $fornecedor->cnpj }} </td>
                                <td style="text-align: right;" >
                                   
                                    <a href="{{ route('fornecedores.show',$fornecedor->id) }}" class="btn btn-info btn-group"><i class="fa fa-eye" aria-hidden="true"></i> Ver</a>
                                    
                                    <a href="{{ route('fornecedores.edit',$fornecedor->id) }}" class="btn btn-warning btn-group"><i class="fa fa-edit" aria-hidden="true"></i> Atualizar</a>
                                    
                                </td>
                            </tr>
                        
                    @empty
                        <p>Não foram encontrados registros</p>
                    @endforelse
                </tbody>      
            </table>

    	</div>
    </div>
@stop